### ISSUE TITLE
Would you accept Simon game project in js?

### ISSUE THREAD

**Issue by priyanshu-kun** [Techsalicious/Hacktoberfest-2020#44]

**Comment by Shirsha-Singha** [comment]
What do you mean by Simon game project? Do you mean the assisted mobility for older and impaired persons?

**Comment by priyanshu-kun** [comment]
Yup Simon game project and I think my PR was closed so will you tell me how can I contribute in your ripo.

**Comment by Shirsha-Singha** [comment]
Just create a PR and do the game project!

**Comment by priyanshu-kun** [comment]
I was create a PR please check it and if you like so please accept it:D

**Comment by Shirsha-Singha** [comment]
Everything is done, Happy Hacking!
